services:
  sherlock-frontend:
    image: arturoalvarez/sherlock-frontend:latest
    container_name: sherlock-frontend
    ports:
      - "3012:80"
    networks:
      - sherlock-internal
    restart: unless-stopped
    environment:
      - API_URL=http://sherlock-backend:5000
    depends_on:
      - sherlock-backend

  sherlock-backend:
    image: arturoalvarez/sherlock-backend:latest
    container_name: sherlock-backend
    ports:
      - "5000:5000"
    networks:
      - sherlock-internal
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

networks:
  sherlock-internal:
    driver: bridge
